name: Actions
run-name: ${{ github.actor }}
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Nodo.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: CXXFLAGS="--std=c++14" npm install
      - name: build production project
        run: npm run build:prod
      - name: testing
        run: npm run test
      - name: storybook
        run: npm run build-storybook
